import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import type { Metadata } from 'next'
import '@/styles/globals.scss'

import { Open_Sans } from 'next/font/google'
const mainFont = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Root website layout
export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        <div id="contentBody">
          <Navbar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
